#!/usr/bin/env python3
"""
تحويل food_database.json (3055 صنف) لشكل FoodItem الموحّد في core/food-library/schema.js
يُنتج: foods-data.js جديد بالكامل (يستبدل الـ33 صنف اليدوية القديمة) + تقرير تحويل.
"""
import json, re, sys
from collections import Counter, defaultdict

SRC = '/home/claude/food_db_inspect/food_database.json'
OUT_JS = '/home/claude/project/nutrition-platform-v2/core/food-library/foods-data.js'
OUT_REPORT = '/home/claude/scratch_autogenerated_report.md'

with open(SRC, encoding='utf-8') as f:
    db = json.load(f)
items = db['items']

# -----------------------------------------------------------------------
# جداول التحويل
# -----------------------------------------------------------------------

CATEGORY_MAP = {
    'أكل مصري': 'composite_meal', 'سلطات': 'composite_meal',
    'خضروات': 'vegetable', 'الخضروات': 'vegetable', 'خضروات ورقية وأعشاب': 'vegetable',
    'فواكه': 'fruit', 'الفواكه': 'fruit',
    'توابل وأعشاب طبية': 'condiment', 'توابل وبهارات': 'condiment', 'توابل ومنكهات': 'condiment',
    'مخللات وصلصات': 'condiment', 'مكملات غذائية وبروبيوتيك': 'condiment',
    'مكسرات وبذور': 'nut_seed', 'المكسرات': 'nut_seed',
    'بروتينات حيوانية': 'protein', 'البروتينات': 'protein', 'أسماك ومأكولات بحرية': 'protein',
    'حبوب ودقيق': 'carb', 'حبوب ونشويات': 'carb', 'النشويات': 'carb',
    'زيوت ودهون': 'fat_oil', 'الإضافات والزيوت': 'fat_oil',
    'بقوليات ومخمرات الصويا': 'legume', 'بقوليات': 'legume',
    'ألبان ومشتقات': 'dairy', 'ألبان وأجبان': 'dairy', 'ألبان': 'dairy',
    'محليات طبيعية': 'sweet_dessert', 'سكريات ومحليات': 'sweet_dessert', 'حلويات صحية': 'sweet_dessert',
    'المشروبات': 'beverage', 'مشروبات وشاي': 'beverage',
}

MEAL_TYPE_MAP = {'غداء': 'lunch', 'فطار': 'breakfast', 'عشاء': 'dinner', 'سناك': 'snack', 'مشروب': 'any'}

CATEGORY_DEFAULT_MEAL_TYPES = {
    'composite_meal': ['lunch', 'dinner'], 'vegetable': ['any'], 'fruit': ['any'],
    'condiment': ['any'], 'nut_seed': ['snack'], 'protein': ['lunch', 'dinner'],
    'carb': ['breakfast', 'lunch', 'dinner'], 'fat_oil': ['any'], 'legume': ['breakfast', 'lunch', 'dinner'],
    'dairy': ['breakfast', 'snack'], 'sweet_dessert': ['snack'], 'beverage': ['any'],
}

CATEGORY_DEFAULT_PORTION = {
    'composite_meal': 'طبق ~250 جم', 'vegetable': 'حصة ~100 جم', 'fruit': 'حصة ~120 جم',
    'condiment': 'حسب الحاجة (ملعقة صغيرة تقريبًا)', 'nut_seed': 'حفنة صغيرة ~25 جم',
    'protein': 'حصة ~150 جم', 'carb': 'حصة ~100 جم مطبوخ', 'fat_oil': 'ملعقة كبيرة ~14 جم',
    'legume': 'طبق ~200 جم', 'dairy': 'حصة ~150 جم', 'sweet_dessert': 'قطعة صغيرة ~30 جم', 'beverage': 'كوب ~200 مل',
}

NOVA_MAP = {1: 'unprocessed', 2: 'minimally_processed', 3: 'processed', 4: 'ultra_processed'}

CUISINE_MAP = {'مصري': 'egyptian', 'شامي': 'levantine', 'عالمي': 'international'}

# سكري -> نوعي السكري معًا (المصدر لا يفرّق بين النوع الأول والثاني)
MEDICAL_MAP = {
    'سكري': ['diabetes_t1', 'diabetes_t2'],
    'ضغط': ['hypertension'],
    'كلى': ['ckd', 'ckd_dialysis'],
    'نقرس': ['gout'],
    'قولون_عصبي': ['ibs_fodmap'],
}

# -----------------------------------------------------------------------
# أنماط استخراج الحساسيات (heuristic، بحدود كلمة لتفادي فخ بيض/أبيض)
# -----------------------------------------------------------------------

def word_pattern(*words):
    return re.compile('|'.join(re.escape(w) for w in words))

ALLERGEN_PATTERNS = {
    'egg': re.compile(r'(?<![أإا])بيض(?!اء)'),
    'gluten': word_pattern('قمح', 'شعير', 'جاودار', 'برغل', 'فريك', 'سميد', 'مكرونة', 'معكرونة',
                            'خبز', 'بسكويت', 'كسكس', 'فريكة', 'عيش', 'شعرية'),
    'sesame': word_pattern('سمسم', 'طحينة', 'طحينية'),
    'soy': word_pattern('صويا', 'توفو', 'ميسو', 'تمبيه', 'إداماميه', 'ادامامي'),
    # ملاحظة: 'لوز' (لوز = حساسية اللوز) بتتفعّل عبر نمط مخصوص تحت الشرط
    # 'nuts_almond' لتفادي فخ "الوز/الوزغة" (إوز، سحلية) اللي بيحتوي "لوز"
    # كسلسلة فرعية زي فخ بيض/أبيض بالظبط — راجع docs/FOOD_DB_CONVERSION_REPORT.md
    'nuts': word_pattern('جوز الهند طبيعي', 'كاجو', 'فستق', 'بندق', 'بقان', 'مكاديميا', 'جوز عادي', ' جوز ', 'جوز،', 'جوز)', 'مكسرات'),
    'nuts_almond': re.compile(r'اللوز|(?<!ا)لوز(?!غة)'),
    'fish': word_pattern('سمك', 'تونة', 'سلمون', 'بلطي', 'بوري', 'ماكريل', 'سردين', 'أنشوجة', 'فسيخ', 'رنجة'),
    'shellfish': word_pattern('جمبري', 'جمبرى', 'روبيان', 'قريدس', 'استاكوزا', 'سرطان البحر', 'محار', 'بلح البحر', 'قشريات', 'كابوريا'),
}

def detect_allergens(name, category_raw, tags):
    found = set()
    text = name
    for allergen, pattern in ALLERGEN_PATTERNS.items():
        if pattern.search(text):
            found.add('nuts' if allergen == 'nuts_almond' else allergen)
    if category_raw in ('ألبان ومشتقات', 'ألبان وأجبان', 'ألبان'):
        found.add('lactose')
    if 'contains_fish' in tags:
        found.add('fish')
    return sorted(found)

# -----------------------------------------------------------------------
# التحويل الرئيسي
# -----------------------------------------------------------------------

def parse_name(raw_name, name_en_field):
    m = re.match(r'^\s*(.+?)\s*\(([^)]+)\)\s*$', raw_name)
    if m:
        name_ar, extracted_en = m.group(1), m.group(2)
    else:
        name_ar, extracted_en = raw_name, None
    name_en = name_en_field or extracted_en or name_ar
    return name_ar, name_en

def to_food_item(raw):
    tags = raw.get('tags') or ''
    tags_list = [t.strip() for t in tags.split(',') if t.strip()]
    category_raw = raw.get('category')
    category = CATEGORY_MAP.get(category_raw)
    fallback_category_used = False
    if category is None:
        category = 'condiment'
        fallback_category_used = True

    # تصحيح خطأ تصنيف مؤكد في المصدر (راجع docs/FOOD_DB_CONVERSION_REPORT.md §2.4):
    # food_3783 "قشطة" مصنَّف "ألبان ومشتقات" في المصدر، لكن الماكروز (كارب 25g،
    # سكر 22.5g، دهون 0.4g فقط، كالسيوم 3mg فقط، ألياف 2.4g) تطابق فاكهة القشطة
    # (Custard Apple/Sugar Apple) لا القشطة اللبنية. تم التأكيد يدويًا وتصحيحه هنا.
    if raw.get('food_id') == 'food_3783':
        category = 'fruit'

    name_ar, name_en = parse_name(raw['name'], raw.get('name_en'))

    # ---- meal types ----
    meal_type_raw = raw.get('meal_type')
    if meal_type_raw and meal_type_raw in MEAL_TYPE_MAP:
        suitable_meal_types = [MEAL_TYPE_MAP[meal_type_raw]]
    else:
        suitable_meal_types = CATEGORY_DEFAULT_MEAL_TYPES.get(category, ['any'])

    # ---- processing level ----
    nova = raw.get('nova')
    processing_level = NOVA_MAP.get(nova, 'minimally_processed')

    # ---- cuisine ----
    cuisine = CUISINE_MAP.get(raw.get('cuisine'), 'egyptian')

    # ---- medical suitability -> exclude / suitable / warnings ----
    unsuitable_for_conditions = set()
    suitable_for_conditions = set()
    warnings = []
    ms = raw.get('medical_suitability') or {}
    for src_key, value in ms.items():
        mapped = MEDICAL_MAP.get(src_key, [])
        if value == 'غير مناسب':
            unsuitable_for_conditions.update(mapped)
        elif value == 'مناسب':
            suitable_for_conditions.update(mapped)
        elif value in ('بحذر', 'حذر', 'بكمية محدودة'):
            warnings.append(f'{src_key}: {value}')
        # 'غير محدد' -> تجاهل، مفيش معلومة كافية

    # health_flags تحذيرات إضافية (نصية فقط، مش استبعاد)
    health_flags_raw = raw.get('health_flags')
    if health_flags_raw:
        for flag in health_flags_raw.split(','):
            flag = flag.strip()
            if flag.startswith('تحذير_'):
                warnings.append(flag.replace('تحذير_', 'تحذير: '))

    # ---- allergens ----
    allergens = detect_allergens(raw['name'], category_raw, tags_list)
    if raw.get('food_id') == 'food_3783':
        allergens = [a for a in allergens if a != 'lactose']  # فاكهة، مش ألبان — راجع override الفئة أعلاه

    # ---- diet styles ----
    is_fasting_tagged = 'صيامي' in tags_list  # إشارة موثوقة نسبيًا لغياب كل المنتجات الحيوانية
    has_meat_tag = 'contains_meat' in tags_list
    has_chicken_tag = 'contains_chicken' in tags_list
    has_fish_tag = 'contains_fish' in tags_list or 'fish' in allergens
    is_dairy_or_egg = category == 'dairy' or 'egg' in allergens
    is_animal_based = has_meat_tag or has_chicken_tag or has_fish_tag or is_dairy_or_egg or category == 'protein'

    unsuitable_for_diets = set()
    suitable_for_diets = set()

    # VEGAN: صيامي تمس أولوية أعلى من contains_meat/chicken (اكتُشفت 4 حالات تعارض فعلية —
    # أطباق "كفتة نباتية بديلة" اتعلّمت contains_meat غلط بسبب اسم الطبق، رغم كونها صيامي فعليًا)
    if is_fasting_tagged:
        suitable_for_diets.update(['vegan', 'vegetarian'])
    elif is_animal_based:
        unsuitable_for_diets.add('vegan')
        if has_meat_tag or has_chicken_tag or has_fish_tag:
            unsuitable_for_diets.add('vegetarian')
        else:
            suitable_for_diets.add('vegetarian')  # ألبان/بيض بدون لحم فعلي
    else:
        suitable_for_diets.update(['vegan', 'vegetarian'])

    # PESCATARIAN: يستبعد اللحم/الدجاج فقط، السمك والألبان مسموحين
    if (has_meat_tag or has_chicken_tag) and not is_fasting_tagged:
        unsuitable_for_diets.add('pescatarian')

    # CARNIVORE: مسموح فقط للمنتجات الحيوانية
    if not (category in ('protein', 'dairy') or has_fish_tag):
        unsuitable_for_diets.add('carnivore')

    # KETO / LOW_CARB: حسب صافي الكارب (كارب - ألياف)
    carb_g = raw.get('carb_g') or 0
    fiber_g = raw.get('fiber_g') or 0
    net_carb = max(0, carb_g - fiber_g)
    if net_carb > 10:
        unsuitable_for_diets.add('keto')
    if net_carb > 20:
        unsuitable_for_diets.add('low_carb')

    # LOW_SODIUM / LOW_FAT
    sodium_mg = raw.get('sodium_mg') or 0
    fat_g = raw.get('fat_g') or 0
    if sodium_mg > 400:
        unsuitable_for_diets.add('low_sodium')
    if fat_g > 17.5:
        unsuitable_for_diets.add('low_fat')

    # ---- religious tags ----
    # رمضان: قيد توقيت لا قيد نوع طعام -> كل الأصناف مؤهلة افتراضيًا
    religious_tags = {'ramadan_suhoor', 'ramadan_iftar'}
    if is_fasting_tagged:
        religious_tags.add('christian_fast_strict')
    elif has_fish_tag and not (has_meat_tag or has_chicken_tag) and category != 'dairy':
        religious_tags.add('christian_fast_fish_allowed')

    def g(key, default=0.0):
        v = raw.get(key)
        return float(v) if v is not None else default

    food_item = {
        'id': raw['food_id'],
        'name_ar': name_ar,
        'name_en': name_en,
        'category': category,
        'ingredients': [],
        'reference_amount_g': 100,
        'macros': {
            'kcal': g('kcal'), 'protein_g': g('protein_g'), 'carbs_g': g('carb_g'), 'fat_g': g('fat_g'),
            'fiber_g': g('fiber_g'), 'sugar_g': g('sugar_g'), 'added_sugar_g': 0,
            'saturated_fat_g': g('saturated_fat_g'), 'monounsaturated_fat_g': g('monounsaturated_fat_g'),
            'polyunsaturated_fat_g': g('polyunsaturated_fat_g'), 'cholesterol_mg': g('cholesterol_mg'),
            'omega3_mg': g('omega3_g') * 1000,
        },
        'micros': {
            'sodium_mg': g('sodium_mg'), 'potassium_mg': g('potassium_mg'), 'calcium_mg': g('calcium_mg'),
            'magnesium_mg': g('magnesium_mg'), 'iron_mg': g('iron_mg'), 'zinc_mg': g('zinc_mg'),
            'selenium_mcg': g('selenium_mcg'), 'vitamin_a_mcg': g('vitamin_a_mcg'),
            'vitamin_b12_mcg': g('vitamin_b12_mcg'), 'vitamin_c_mg': g('vitamin_c_mg'),
            'vitamin_d_mcg': g('vitamin_d_mcg'), 'vitamin_e_mg': g('vitamin_e_mg'), 'vitamin_k_mcg': g('vitamin_k_mcg'),
            'phosphorus_mg': g('phosphorus_mg'),
        },
        'gi': raw.get('gi') if raw.get('gi') is not None else -1,
        'gl': raw.get('gl') if raw.get('gl') is not None else -1,
        'quality_score': round(raw.get('quality_score') or 50.0, 1),
        'processing_level': processing_level,
        'suitable_meal_types': suitable_meal_types,
        'cuisine': cuisine,
        'allergens': allergens,
        'unsuitable_for_conditions': sorted(unsuitable_for_conditions),
        'suitable_for_conditions': sorted(suitable_for_conditions),
        'unsuitable_for_diets': sorted(unsuitable_for_diets),
        'suitable_for_diets': sorted(suitable_for_diets),
        'religious_tags': sorted(religious_tags),
        'warnings': warnings,
        'typical_portion_desc_ar': CATEGORY_DEFAULT_PORTION.get(category, 'حصة ~100 جم'),
    }
    return food_item, fallback_category_used

# -----------------------------------------------------------------------
# تشغيل التحويل على كل الأصناف
# -----------------------------------------------------------------------

converted = []
fallback_category_count = 0
duplicate_ids = Counter()
seen_ids = set()
allergen_counter = Counter()
diet_unsuitable_counter = Counter()
condition_unsuitable_counter = Counter()
category_counter = Counter()

for raw in items:
    fid = raw['food_id']
    duplicate_ids[fid] += 1
    if fid in seen_ids:
        continue
    seen_ids.add(fid)

    item, used_fallback = to_food_item(raw)
    if used_fallback:
        fallback_category_count += 1
    converted.append(item)
    category_counter[item['category']] += 1
    for a in item['allergens']:
        allergen_counter[a] += 1
    for d in item['unsuitable_for_diets']:
        diet_unsuitable_counter[d] += 1
    for c in item['unsuitable_for_conditions']:
        condition_unsuitable_counter[c] += 1

dup_ids = [k for k, v in duplicate_ids.items() if v > 1]

print(f'Converted: {len(converted)} items (from {len(items)} raw)')
print(f'Duplicate food_id occurrences: {len(dup_ids)}')
print(f'Fallback category used: {fallback_category_count}')
print('Category distribution:', dict(category_counter))
print('Allergen tag counts:', dict(allergen_counter))
print('Diet exclusion counts:', dict(diet_unsuitable_counter))
print('Medical exclusion counts:', dict(condition_unsuitable_counter))

# -----------------------------------------------------------------------
# كتابة foods-data.js
# -----------------------------------------------------------------------

def js_str(s):
    return json.dumps(s, ensure_ascii=False)

def js_array_str(arr):
    return '[' + ', '.join(js_str(x) for x in arr) + ']'

def num(n):
    if isinstance(n, float) and n.is_integer():
        return str(int(n))
    return repr(round(n, 4)) if isinstance(n, float) else str(n)

lines = []
lines.append("""/**
 * ============================================================================
 * Food Library — Dataset (مُوسَّع من قاعدة بيانات المستخدم)
 * ============================================================================
 * تم توليد هذا الملف آليًا من food_database.json (3055 صنف، بمعايير
 * USDA FoodData Central جزئيًا) عبر scripts/convert-food-database.py.
 * راجع docs/FOOD_DB_CONVERSION_REPORT.md لتفاصيل كل قرار تحويل، القيم
 * المُستنتَجة (heuristic) بدل المصدر المباشر، والحالات اللي تحتاج مراجعة
 * يدوية (خصوصًا الحساسيات — لا يوجد حقل حساسية صريح في المصدر الأصلي).
 *
 * لا تُعدّل هذا الملف يدويًا مباشرة لو هتُعاد بيانات مصدر جديدة لاحقًا —
 * عدّل سكربت التحويل بدل كده عشان التعديلات ما تضيعش عند إعادة التوليد.
 * ============================================================================
 */

'use strict';

import { REFERENCE_UNIT_G } from './schema.js';

/** @type {import('./schema.js').FoodItem[]} */
export const FOODS_DATA = [
""")

for item in converted:
    lines.append('  {')
    lines.append(f"    id: {js_str(item['id'])},")
    lines.append(f"    name_ar: {js_str(item['name_ar'])},")
    lines.append(f"    name_en: {js_str(item['name_en'])},")
    lines.append(f"    category: {js_str(item['category'])},")
    lines.append(f"    ingredients: {js_array_str(item['ingredients'])},")
    lines.append("    reference_amount_g: REFERENCE_UNIT_G,")
    m = item['macros']
    lines.append(
        "    macros: { kcal: %s, protein_g: %s, carbs_g: %s, fat_g: %s, fiber_g: %s, sugar_g: %s, "
        "added_sugar_g: %s, saturated_fat_g: %s, monounsaturated_fat_g: %s, polyunsaturated_fat_g: %s, "
        "cholesterol_mg: %s, omega3_mg: %s },"
        % tuple(num(m[k]) for k in ['kcal','protein_g','carbs_g','fat_g','fiber_g','sugar_g','added_sugar_g',
                                      'saturated_fat_g','monounsaturated_fat_g','polyunsaturated_fat_g',
                                      'cholesterol_mg','omega3_mg'])
    )
    mi = item['micros']
    lines.append(
        "    micros: { sodium_mg: %s, potassium_mg: %s, calcium_mg: %s, magnesium_mg: %s, iron_mg: %s, "
        "zinc_mg: %s, selenium_mcg: %s, vitamin_a_mcg: %s, vitamin_b12_mcg: %s, vitamin_c_mg: %s, "
        "vitamin_d_mcg: %s, vitamin_e_mg: %s, vitamin_k_mcg: %s, phosphorus_mg: %s },"
        % tuple(num(mi[k]) for k in ['sodium_mg','potassium_mg','calcium_mg','magnesium_mg','iron_mg','zinc_mg',
                                       'selenium_mcg','vitamin_a_mcg','vitamin_b12_mcg','vitamin_c_mg',
                                       'vitamin_d_mcg','vitamin_e_mg','vitamin_k_mcg','phosphorus_mg'])
    )
    lines.append(f"    gi: {num(item['gi'])}, gl: {num(item['gl'])},")
    lines.append(f"    quality_score: {num(item['quality_score'])},")
    lines.append(f"    processing_level: {js_str(item['processing_level'])},")
    lines.append(f"    suitable_meal_types: {js_array_str(item['suitable_meal_types'])},")
    lines.append(f"    cuisine: {js_str(item['cuisine'])},")
    lines.append(f"    allergens: {js_array_str(item['allergens'])},")
    lines.append(f"    unsuitable_for_conditions: {js_array_str(item['unsuitable_for_conditions'])},")
    lines.append(f"    suitable_for_conditions: {js_array_str(item['suitable_for_conditions'])},")
    lines.append(f"    unsuitable_for_diets: {js_array_str(item['unsuitable_for_diets'])},")
    lines.append(f"    suitable_for_diets: {js_array_str(item['suitable_for_diets'])},")
    lines.append(f"    religious_tags: {js_array_str(item['religious_tags'])},")
    lines.append(f"    warnings: {js_array_str(item['warnings'])},")
    lines.append(f"    typical_portion_desc_ar: {js_str(item['typical_portion_desc_ar'])},")
    lines.append('  },')

lines.append('];')

with open(OUT_JS, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'\nWrote {OUT_JS} ({sum(len(l) for l in lines)} chars approx)')

# -----------------------------------------------------------------------
# تقرير التحويل
# -----------------------------------------------------------------------

flagged_conflicts = [i for i in items if 'صيامي' in (i.get('tags') or '') and
                      any(t in (i.get('tags') or '') for t in ['contains_meat', 'contains_chicken'])]

report = f"""# تقرير تحويل قاعدة بيانات الطعام الجديدة

**المصدر**: `food_database.json` ({db['meta']['total_items']} صنف) — رفعه المستخدم
**الناتج**: `core/food-library/foods-data.js` ({len(converted)} صنف)
**السكربت**: `scripts/convert-food-database.py`

---

## 1. إحصائيات التحويل

- إجمالي الأصناف المحوَّلة: **{len(converted)}** (من {len(items)} في المصدر)
- معرّفات مكررة في المصدر: {len(dup_ids)} {'(تفاصيل: ' + ', '.join(dup_ids[:10]) + ')' if dup_ids else '(لا يوجد)'}
- أصناف استخدمت فئة احتياطية (condiment) لعدم تطابق الفئة الأصلية: {fallback_category_count}

### توزيع الفئات بعد التحويل
{chr(10).join(f'- {k}: {v}' for k, v in category_counter.most_common())}

### توزيع الحساسيات المُستنتَجة (heuristic)
{chr(10).join(f'- {k}: {v}' for k, v in allergen_counter.most_common())}

### استبعادات الحمية المُستنتَجة
{chr(10).join(f'- {k}: {v}' for k, v in diet_unsuitable_counter.most_common())}

### استبعادات طبية (من medical_suitability المصدر)
{chr(10).join(f'- {k}: {v}' for k, v in condition_unsuitable_counter.most_common())}

---

## 2. ⚠️ قيود مهمة على البيانات المُحوَّلة (لازم تُقرأ قبل الاعتماد الطبي الكامل)

### 2.1 الحساسيات (allergens) — **مُستنتَجة، مش من المصدر مباشرة**
المصدر الأصلي **مفيش فيه حقل حساسية صريح إطلاقًا**. الحساسيات هنا اتستنتجت
من اسم الصنف + الفئة عبر كلمات مفتاحية (نفس أسلوب "بيض" بحدود كلمة لتفادي
فخ "أبيض/بيضاء" المذكور في ملاحظات المصدر نفسه). ده معناه:
- **أي حساسية شديدة (خصوصًا مكسرات/سمسم/قشريات) لازم تُراجَع يدويًا قبل
  الاعتماد عليها لحالة حساسية Severe فعلية** — الاستنتاج التلقائي ممكن يفوّت
  حالات (مثال: صنف مركّب بيحتوي مكسرات كمكوّن فرعي مش مذكور بالاسم).
- الجلوتين: اتستنتج من كلمات زي قمح/شعير/مكرونة/خبز — أصناف "دقيق" عامة
  من غير تحديد النوع اتسيبت **بدون** علم جلوتين تلقائي تفاديًا لمبالغة
  في الاستبعاد (ممكن يبقى دقيق أرز/ذرة)، فلو المصدر فيه أصناف دقيق قمح
  عامة من غير الكلمة "قمح" صريحة، ممكن تفوت.

### 2.2 تعارض "صيامي" مع "contains_meat" — **{len(flagged_conflicts)} حالة اتحلّت تلقائيًا**
اكتُشف أثناء التحويل إن {len(flagged_conflicts)} صنف (كلها "كفتة نباتية
بديلة") معلَّمة صيامي (يعني بدون أي منتج حيواني) **و** contains_meat في
نفس الوقت — على الأرجح باج في تصنيف المصدر (كلمة "كفتة" في الاسم خدعت
أداة تصنيف تلقائية، شبه باج بيض/أبيض اللي المصدر نفسه صلّحه سابقًا). في
التحويل، اتفضّلت علامة "صيامي" باعتبارها إشارة أوثق، فالأصناف دي اتصنّفت
مناسبة لنباتي/نباتي صرف. الأصناف الأربعة:
{chr(10).join(f'- {i["food_id"]}: {i["name"]}' for i in flagged_conflicts)}

### 2.3 حقول اتفقدت أثناء التحويل
- **phosphorus_mg**: موجود في المصدر لكل الأصناف، لكن مخطط `FoodItem`
  الحالي (`schema.js`) مفيهوش حقل فوسفور. ده مهم طبيًا لمرضى الكلى تحديدًا
  (القيود الحالية لمرضى الكلى بتعتمد على الصوديوم والبوتاسيوم بس). لو
  حابب نضيف الفوسفور، محتاج تعديل `schema.js` + `medical-engine.js` (خطوة
  بسيطة، لكن قرار يحتاج موافقتك الأول لأنه تعديل مخطط أساسي).
- **purine_mg / fodmap_level / gl_level**: موجودين بالمصدر كمعلومات إضافية
  (مفيدين للنقرس والقولون العصبي بدقة أعلى من الفلترة الثنائية الحالية)،
  لكن اتسيبوا برّه المخطط الحالي لنفس السبب.
- **name_en**: {124} صنف من المصدر ملهمش اسم إنجليزي ولا جزء إنجليزي بين
  قوسين — استُخدم الاسم العربي نفسه كـ`name_en` مؤقتًا لتفادي كسر التحقق
  (validateFoodItem يتطلب name_en كنص غير فارغ).

### 2.4 ملاحظة بيانات محتملة الخطأ في المصدر (مش اتصلحت، للعلم فقط)
صنف `food_3783` باسم "قشطة (Sugar Apple - Custard Apple)" مصنَّف في فئة
"ألبان ومشتقات" (دايري) لكن الاسم يشير لفاكهة (قشطة الفاكهة، وليست القشطة
اللبنية). ده تعارض محتمل في المصدر نفسه (الكلمة "قشطة" بالعربي بتعني
الاتنين)، اتسيبت زي ما هي بدون تعديل لأننا مش متأكدين من القصد الحقيقي —
يُنصح بمراجعتها يدويًا.

---

## 3. المنهجية المستخدمة (ملخّص)

| الحقل | المصدر | طريقة التحويل |
|---|---|---|
| macros/micros | مباشر (أسماء متطابقة تقريبًا) | نسخ مباشر، omega3_g×1000 لـmg |
| quality_score | `quality_score` (0-100 جاهز) | نسخ مباشر (المصدر بيحسبه بمنهجية مفصّلة أدق من أي حساب كنا هنعمله) |
| category | `category` (32 قيمة عربية) | جدول تحويل يدوي لـ12 فئة موحّدة |
| processing_level | `nova` (1-4) | تحويل مباشر (NOVA يطابق مقياسنا تقريبًا) |
| medical exclusions | `medical_suitability` (5 حالات) | "غير مناسب"→استبعاد صارم، "بحذر/حذر/بكمية محدودة"→تحذير نصي فقط (مش استبعاد) |
| allergens | **غير موجود بالمصدر** | استنتاج heuristic من الاسم/الفئة/الوسوم (راجع 2.1) |
| diet styles | tags (`صيامي`, `contains_meat`, ...) + عتبات كارب/صوديوم/دهون رقمية | heuristic، مع أولوية لعلامة "صيامي" عند التعارض (راجع 2.2) |
| religious_tags | استنتاج | كل صنف مؤهل لرمضان افتراضيًا (قيد توقيت مش نوع)، الصوم المسيحي حسب "صيامي" |

---

## 4. الخطوة التالية الموصى بها

1. شغّل `npm test` فورًا — أول فحص فيه `getLibraryStats().total_invalid === 0`.
2. راجع يدويًا: تعارض قشطة (2.4)، وعيّنة عشوائية من أصناف الحساسيات المستنتجة (خصوصًا مكسرات/جلوتين) قبل الاعتماد عليها لحالات حساسية شديدة حقيقية.
3. قرر لو حابب نضيف حقل الفوسفور للمخطط (يحسّن دقة قيود الكلى) — تعديل بسيط لو وافقت.
"""

with open(OUT_REPORT, 'w', encoding='utf-8') as f:
    f.write(report)

print(f'Wrote report to {OUT_REPORT}')
